homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: eexaighii9phie4jaasie9ohm7Ahl9sahr1eine9xien4arah1giaCooph9lieYu
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_180be99befe7ec119d767c60e89bdf6f-if00-port0
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
device_options:
  legacy: false
devices:
  '0x001788010d671a5f':
    friendly_name: kallax
  '0x001788010d653304':
    friendly_name: hanging
  '0x001788010d3b4457':
    friendly_name: bedside
  '0xf082c0fffe0fa93b':
    friendly_name: bed
  '0x94b216fffeb50df8':
    friendly_name: wall
groups:
  '1':
    friendly_name: all
    devices:
      - 0x001788010d653304/11
      - 0x001788010d671a5f/11
      - 0x001788010d3b4457/11
